### ISSUE TITLE
Issue with node 2

### ISSUE THREAD

**Issue by ashishstats** [sandeepyadav1478/Transfer-files-from-google-to-terabox-cloud#5]
When I ran this code

# downloading anytype of file from server
import urllib.request
# following variable keep target file location with file extension
tar_loc="10.zip"
# It is google photos export download link
urllib.request.urlretrieve('https://00f74ba44b06ad2b25331f2222d0a6d55fd7beefcb-apidata.googleusercontent.com/download/storage/v1/b/dataliberation/o/20210531T101632Z%2F7404861098411033338%2F121bdc54-40a4-427c-b8ca-882a6e8b3d56%2F1%2F38af1e43-9dbf-42c4-9bf2-2f4f7e48e461?jk=AFshE3WvL6UYYr--0UO14GbtXUT2XMMJi0oQHYI7UPZ6JTrIjCpqaS6pG7cDfgB4gmIcIv0E4H70nveONj85dX-JAYVlOLvchlHjELfzrDfb6-ilfm3dt7v9QWJs0N0Wj32h7JFRGccO3ff1-F3OtB2UYk5TKG8DK5S3NEfTSShFa-cYdC8AhE7tn8M1w8nouvBh6-UtxFgSYV919G-23DxC9BheLWhxeg_xT6wkEWXqmZu7GWWr39kl5SCAqhz4ONhjEkhRISH7KlomtJhIF52Us3P8smV1SzlQLsap5BIcZftwvbV4Y3mW3MUSRZ_Nk39Y42iO2J3-3oxzwejCW6oop7LKjIKjg-5wuygPw6butE8uoMC09wntfGEtqh_4ZyVtqMN1bKQgvYv7e0b9GPP5ZowWY12V3jFyJ9Zit3ZWqcGQZS_e7b42vsCb62Le1MAYbTUFje45VenOOilw9IjE6gZWdOtK9RAQ9CNCZaMPDHpVK7C7M9RgxuOCNqoAbinTZ5g4XHU6mufLnwMKu092HrfhalrlQMEylRv99wV50J-6p6e_MgSWJ7S0TAL9miFw_sgymXmD9Ry84zPBixIjz3w3eN79NQtmzyJbsV6kR2HwgEYonQAoaUfaLGggKi3CehOCl5VaTFCdeXboXxTweKBzq1hwMUVz6Ss2UKSl42vItFSh15uWvZ5pEocXqRwIs-_f5o8lm_7n7uXlyRFdDY1gS6ISDkKWD2vsftdTM94cLL5MAhhdF68Mn6pQ_kDNYiBUF2hohqib1sFij_4ULikWngT6ctZzQ5SSY7EnZJiWlAzeYZeJa0mbyCa1gsbOUX60K8OjIxjJpJP8u1NLeX9ALYj84kiCQljxTBaPNhKt28_0oE-5PcfHEP5JJzizS1SE3Sjh8131Wm6gg2MJSsSwvNOZDQ0awJN9XmeFaD2Iz0xA5aMzNarrbFCT0UzagTIL6nDDBE9StDAuD1rXAgVhXt6IpbvktnIBzQfFCX5YPCWqd6x-JaXbWR4IVnn55z9O_WarZwavAeAgvMVznje98SeWIj4FkvUrrz3Z7yfZR_dLF-HCz2dz1ORoFTWa3TxDbEJXT48WkguvwqU&isca=1',tar_loc)

I got this error

HTTPError                                 Traceback (most recent call last)
[<ipython-input-3-763675de37fa>](https://localhost:8080/#) in <module>
      4 tar_loc="10.zip"
      5 # It is google photos export download link
----> 6 urllib.request.urlretrieve('https://00f74ba44b06ad2b25331f2222d0a6d55fd7beefcb-apidata.googleusercontent.com/download/storage/v1/b/dataliberation/o/20210531T101632Z%2F7404861098411033338%2F121bdc54-40a4-427c-b8ca-882a6e8b3d56%2F1%2F38af1e43-9dbf-42c4-9bf2-2f4f7e48e461?jk=AFshE3WvL6UYYr--0UO14GbtXUT2XMMJi0oQHYI7UPZ6JTrIjCpqaS6pG7cDfgB4gmIcIv0E4H70nveONj85dX-JAYVlOLvchlHjELfzrDfb6-ilfm3dt7v9QWJs0N0Wj32h7JFRGccO3ff1-F3OtB2UYk5TKG8DK5S3NEfTSShFa-cYdC8AhE7tn8M1w8nouvBh6-UtxFgSYV919G-23DxC9BheLWhxeg_xT6wkEWXqmZu7GWWr39kl5SCAqhz4ONhjEkhRISH7KlomtJhIF52Us3P8smV1SzlQLsap5BIcZftwvbV4Y3mW3MUSRZ_Nk39Y42iO2J3-3oxzwejCW6oop7LKjIKjg-5wuygPw6butE8uoMC09wntfGEtqh_4ZyVtqMN1bKQgvYv7e0b9GPP5ZowWY12V3jFyJ9Zit3ZWqcGQZS_e7b42vsCb62Le1MAYbTUFje45VenOOilw9IjE6gZWdOtK9RAQ9CNCZaMPDHpVK7C7M9RgxuOCNqoAbinTZ5g4XHU6mufLnwMKu092HrfhalrlQMEylRv99wV50J-6p6e_MgSWJ7S0TAL9miFw_sgymXmD9Ry84zPBixIjz3w3eN79NQtmzyJbsV6kR2HwgEYonQAoaUfaLGggKi3CehOCl5VaTFCdeXboXxTweKBzq1hwMUVz6Ss2UKSl42vItFSh15uWvZ5pEocXqRwIs-_f5o8lm_7n7uXlyRFdDY1gS6ISDkKWD2vsftdTM94cLL5MAhhdF68Mn6pQ_kDNYiBUF2hohqib1sFij_4ULikWngT6ctZzQ5SSY7EnZJiWlAzeYZeJa0mbyCa1gsbOUX60K8OjIxjJpJP8u1NLeX9ALYj84kiCQljxTBaPNhKt28_0oE-5PcfHEP5JJzizS1SE3Sjh8131Wm6gg2MJSsSwvNOZDQ0awJN9XmeFaD2Iz0xA5aMzNarrbFCT0UzagTIL6nDDBE9StDAuD1rXAgVhXt6IpbvktnIBzQfFCX5YPCWqd6x-JaXbWR4IVnn55z9O_WarZwavAeAgvMVznje98SeWIj4FkvUrrz3Z7yfZR_dLF-HCz2dz1ORoFTWa3TxDbEJXT48WkguvwqU&isca=1',...

Please help

Ashish

**Comment by sandeepyadav1478** [comment]
Hey Ashish,

I think, this issue occurring with download link invalidation, maybe it got expired.
Try to re-generate another link and re run the code.

**Comment by sandeepyadav1478** [comment]
Hey Ashish,

I think, this issue occurring with download link invalidation, maybe it got expired.
Try to re-generate another link and re run the code.

**Comment by ashishstats** [comment]
Hi Sandeep

you mean to say the share link of photos and videos from google drive?

**Comment by sandeepyadav1478** [comment]
Can you connect via meet or any video call link?
Caz it will take longer to resolve, I am available only today.

**Comment by ashishstats** [comment]
which link should I share and in which email id?

**Comment by sandeepyadav1478** [comment]
Join this 1, [Meet](https://meet.google.com/gqm-ukun-fdw)

**Comment by DrowsyLad** [comment]
No solutions? Is it fixed? I see no update in the code, is this code even works now?
